# -*- coding: utf-8 -*-
"""WebScraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H2AidQI5nOKAbV_1K15rxiVDrOBrlJkC
"""

import requests
from bs4 import BeautifulSoup
import csv

url = "http://quotes.toscrape.com"
response = requests.get(url)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'html.parser')

    quotes = []
    for quote in soup.find_all('div', class_='quote'):
        text = quote.find('span', class_='text').get_text()
        author = quote.find('small', class_='author').get_text()
        tags = [tag.get_text() for tag in quote.find_all('a', class_='tag')]
        quotes.append([text, author, ", ".join(tags)])

    # Write to CSV file
    with open('quotes.csv', 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["Text", "Author", "Tags"])
        writer.writerows(quotes)
else:
    print("Failed to retrieve the webpage")